In [1]:
from p2pfl.node import Node
import time

/usr/local/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
n=2
nodes = []
for i in range(n):
    node = Node(host="localhost")
    node.start()
    nodes.append(node)
    


INFO:root:Nodo a la escucha en localhost 59676
INFO:root:Nodo a la escucha en localhost 59678


In [3]:
for i in range(len(nodes)-1):
    nodes[i+1].connect_to(nodes[i].host,nodes[i].port)
    time.sleep(0.1)


INFO:root:Conexión aceptada con ('localhost', 59678)


In [4]:
# Check if they are connected
for node in nodes:
    print(len(node.neightboors) == n-1)
    

True
True


In [5]:
nodes[0].set_start_learning()

INFO:root:Broadcasting start learning...
INFO:root:Broadcasting model to all clients...
DEBUG:root:Processing message: ['START_LEARNING', '1']
efectivamente se reconoce el COMANDO
INFO:root:Broadcasting model to all clients...
Params received
Params received
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing

In [7]:
for node in nodes:
    print(node.model)

2.0
2.0
2.0
2.0
2.0


In [7]:
for node in nodes:
    print(node.round)

1
1
1
1
1


In [1]:
for node in nodes:
    print(node.model)

NameError: name 'nodes' is not defined

In [11]:
nodes[0].set_stop_learning()

INFO:root:Stopping learning
INFO:root:Stopping learning
INFO:root:Stopping learning
INFO:root:Stopping learning
INFO:root:Stopping learning


In [55]:
from p2pfl.learning.model import MyNodeLearning
import numpy as np
nl1 = MyNodeLearning(None)


pesos = [val.cpu().numpy() for _, val in nl1.model.state_dict().items()]


arrays = [ np.array2string(a) for a in pesos ]
txt = "|".join(arrays)


for a in txt.split("|"):
    print(a)
    print(np.fromstring(a,dtype=float,sep=" "))
    print("----------")
    


#print(pesos)
#print("----------")
#print(pesos_copia)
    
#txt=
#np.fromstring(txt,like=array)


[[ 0.01700013 -0.00202657 -0.02171957 ... -0.01853876  0.01490386
  -0.00891006]
 [-0.01811369  0.01111963  0.03501726 ... -0.02571347  0.01592484
   0.00897522]
 [ 0.00937013 -0.01602109 -0.01612764 ... -0.0048445   0.01773874
   0.00843355]
 ...
 [ 0.00930244 -0.01235592 -0.03509238 ...  0.02637826 -0.02439705
   0.02636678]
 [-0.00259882 -0.00180632  0.0132384  ...  0.00111574  0.03459569
  -0.0356814 ]
 [ 0.03110098  0.0031391  -0.01866219 ... -0.0112348  -0.00716331
   0.03277582]]
[]
----------
[ 0.03310055 -0.03125035  0.01227049  0.01506457 -0.0121666   0.01009908
  0.01363941  0.00697762  0.00662349  0.03456899  0.00533926 -0.02103855
  0.03163164 -0.00088175 -0.01339702 -0.02912547 -0.01159946 -0.00239607
 -0.01855935 -0.02954929 -0.00774772 -0.0072178  -0.03265165 -0.0051045
  0.02895099 -0.01508762 -0.00365993 -0.01255451  0.03113279 -0.02041463
 -0.02170713  0.02934271  0.01027098  0.02785992 -0.01547625 -0.02106673
  0.02726589 -0.03565474  0.00472037  0.01956816 -0.03142

/var/folders/vm/p9lv42ms7ml71cjvsj4bnbnm0000gn/T/ipykernel_35243/1554814457.py:15: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  print(np.fromstring(a,dtype=float,sep=" "))


In [14]:
from p2pfl.learning.model import MyNodeLearning

nl1 = MyNodeLearning(None)
params = nl1.model.state_dict()

#for layer in params:
    #print(params[layer]*0)
params+params

TypeError: unsupported operand type(s) for +: 'collections.OrderedDict' and 'collections.OrderedDict'

DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']
DEBUG:root:Processing message: ['BEAT']


In [22]:
1111111111111100==111111100

False

In [46]:
        return CommunicationProtocol.PARAMS.encode("utf-8") + (data) + (" \\" + CommunicationProtocol.PARAMS).encode("utf-8")



In [4]:
from p2pfl.learning.model import MyNodeLearning
from p2pfl.agregator import FedAvg
import torch

nl1 = MyNodeLearning(None)
params = nl1.get_parameters()
params1 = nl1.get_parameters()
params2 = nl1.get_parameters()

result = FedAvg.agregate([params])

# Check Results
for layer in params:
    assert eq(params[layer], result[layer]).all()

for layer in params2:
    print(layer)
    params1[layer] = params1[layer]+1
    print(params1[layer])
    params2[layer] = params2[layer]-1
    print(params2[layer])
    
result = FedAvg.agregate([params1.copy(), params2.copy()])

    
    
print("Res")    
print(result["l3.bias"].cpu().numpy())
print("Params")
print(params["l3.bias"].cpu().numpy())

print(result["l3.bias"].cpu().numpy() == params["l3.bias"].cpu().numpy())

# Check Results
for layer in params:
    a = torch.round(params[layer], decimals=2)
    b = torch.round(result[layer], decimals=2)
    print(torch.eq(a, b).all())
    


l1.weight
tensor([[0.9729, 0.9819, 0.9776,  ..., 0.9697, 0.9719, 1.0096],
        [1.0329, 1.0154, 0.9853,  ..., 1.0257, 1.0197, 0.9686],
        [1.0017, 0.9770, 1.0132,  ..., 1.0173, 0.9795, 0.9847],
        ...,
        [1.0044, 1.0041, 0.9707,  ..., 0.9785, 0.9941, 1.0087],
        [1.0018, 1.0014, 1.0299,  ..., 1.0178, 1.0233, 0.9873],
        [1.0010, 1.0287, 1.0002,  ..., 0.9760, 0.9767, 1.0109]])
tensor([[-1.0271, -1.0181, -1.0224,  ..., -1.0303, -1.0281, -0.9904],
        [-0.9671, -0.9846, -1.0147,  ..., -0.9743, -0.9803, -1.0314],
        [-0.9983, -1.0230, -0.9868,  ..., -0.9827, -1.0205, -1.0153],
        ...,
        [-0.9956, -0.9959, -1.0293,  ..., -1.0215, -1.0059, -0.9913],
        [-0.9982, -0.9986, -0.9701,  ..., -0.9822, -0.9767, -1.0127],
        [-0.9990, -0.9713, -0.9998,  ..., -1.0240, -1.0233, -0.9891]])
l1.bias
tensor([0.9946, 1.0205, 1.0004, 1.0176, 0.9964, 0.9854, 0.9709, 0.9708, 0.9744,
        0.9994, 0.9921, 1.0102, 1.0101, 1.0229, 1.0316, 1.0310, 0.9934

In [24]:
0.05378953 == 0.05378953

True

In [8]:
[1,2,3][:-1]

[1, 2]